# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: dubk0ff.unicrumbs::controllers.crumbs.name

# Model Form Field configuration
form: $/dubk0ff/unicrumbs/models/crumb/fields.yaml

# Model Class name
modelClass: Dubk0ff\UniCrumbs\Models\Crumb

# Default redirect location
defaultRedirect: dubk0ff/unicrumbs/crumbs

# Create page
create:
    title: backend::lang.form.create_title
    redirect: dubk0ff/unicrumbs/crumbs/update/:id
    redirectClose: dubk0ff/unicrumbs/crumbs/preview/:id

# Update page
update:
    title: backend::lang.form.update_title
    redirect: dubk0ff/unicrumbs/crumbs
    redirectClose: dubk0ff/unicrumbs/crumbs/preview/:id

# Preview page
preview:
    title: backend::lang.form.preview_title

customMessages:
    flashCreate: dubk0ff.unicrumbs::controllers.crumbs.flash_create
    flashUpdate: dubk0ff.unicrumbs::controllers.crumbs.flash_update
    flashDelete: dubk0ff.unicrumbs::controllers.crumbs.flash_delete
