# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: dubk0ff.unicrumbs::controllers.templates.name

# Model Form Field configuration
form: $/dubk0ff/unicrumbs/models/template/fields.yaml

# Model Class name
modelClass: Dubk0ff\UniCrumbs\Models\Template

# Default redirect location
defaultRedirect: dubk0ff/unicrumbs/templates

# Create page
create:
    title: backend::lang.form.create_title
    redirect: dubk0ff/unicrumbs/templates/update/:id
    redirectClose: dubk0ff/unicrumbs/templates

# Update page
update:
    title: backend::lang.form.update_title
    redirect: dubk0ff/unicrumbs/templates
    redirectClose: dubk0ff/unicrumbs/templates

# Preview page
preview:
    title: backend::lang.form.preview_title

customMessages:
    flashCreate: dubk0ff.unicrumbs::controllers.templates.flash_create
    flashUpdate: dubk0ff.unicrumbs::controllers.templates.flash_update
    flashDelete: dubk0ff.unicrumbs::controllers.templates.flash_delete
