# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    active:
        label: dubk0ff.unicrumbs::models.template.is_active
        type: switch
        conditions:
            - is_active is not true
            - is_active is true
